# TouchPass / Fingerprint
CONFIG_ZMK_TOUCHPASS=y
CONFIG_SERIAL=y

# PC側の設定ツールを使う場合
CONFIG_ZMK_TOUCHPASS_SERIAL_RPC=y

# Required subsystems
CONFIG_USB_DEVICE_STACK=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_CDC_ACM=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_SETTINGS=y
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y
CONFIG_REBOOT=y

# Avoid conflicts with serial/USB console backends
CONFIG_ZMK_USB_LOGGING=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_CONSOLE=n
